//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsking.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultShedule
    {
        public long Id { get; set; }
        public long HabitId { get; set; }
        public long ShedulerValueId { get; set; }
    
        public virtual Habit Habit { get; set; }
        public virtual ShedulerValue ShedulerValue { get; set; }
    }
}
