//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsking.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habit
    {
        public Habit()
        {
            this.DefaultShedules = new HashSet<DefaultShedule>();
            this.UserHabits = new HashSet<UserHabit>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }
        public string Feature { get; set; }
        public string ImageUrl { get; set; }
        public long CategoryId { get; set; }
        public long TypeId { get; set; }
        public string PushText { get; set; }
        public int NumberOfReminder { get; set; }
        public string Background { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DefaultShedule> DefaultShedules { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<UserHabit> UserHabits { get; set; }
    }
}
