//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hsking.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShedulerValue
    {
        public ShedulerValue()
        {
            this.DefaultShedules = new HashSet<DefaultShedule>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<DefaultShedule> DefaultShedules { get; set; }
    }
}
